name: CI tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.6
        uses: actions/setup-python@v2
        with:
          python-version: 3.6

      - name: Install dependencies
        run: |
          python -m pip install -r requirements.txt
          python -m pip install -r test/requirements.txt

      - name: Test with pytest
        run: |
          PYTHONPATH=$PWD python -m pytest test/
