name: CI tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test-generic-framework:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install -e .[tests]

      - name: Check code format with Black
        run: |
          black --check .

      - name: Check code style with Flake8
        if: ${{ always() }}
        run: |
          flake8 .

      - name: Test with pytest
        run: |
          python -m pytest test/


  test-opennmt-tf-framework:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install -e .[tests]
          python -m pip install -r frameworks/opennmt_tf/requirements.txt

      - name: Test with pytest
        run: |
          python -m pytest frameworks/opennmt_tf/test/test.py
